import json
import os
import uuid
import gzip
import base64

root = r"D:\Code\pokemon\Pokemon ChatGame"
exe = root + r"\GameEngine\GameEngine.exe"

queue = "00000000-0000-0000-0000-000000000000"

meta = {
    "name": "Pokemon Chat Game Full Import (C# Runner)",
    "author": "auto-generated",
    "version": "1.0.0",
    "description": "Actions + Commands for Pokemon Chat Game (C# runs EXE and sends stdout)",
    "autoRunAction": None,
    "minimumVersion": None,
}


def csharp_bytecode(args: str) -> str:
    lines = [
        "using System;",
        "using System.Diagnostics;",
        "using System.IO;",
        "using System.Linq;",
        "",
        "public class CPHInline",
        "{",
        "    private string GetArgValue(string[] names)",
        "    {",
        "        foreach (var name in names)",
        "        {",
        "            if (CPH.TryGetArg<string>(name, out string value) && !string.IsNullOrWhiteSpace(value))",
        "            {",
        "                return value.Trim();",
        "            }",
        "        }",
        "        return string.Empty;",
        "    }",
        "",
        "    private void SendMsg(string message)",
        "    {",
        "        CPH.SendMessage(message);",
        "        CPH.SendYouTubeMessage(message);",
        "    }",
        "",
        "    public bool Execute()",
        "    {",
        "        string gameRoot = CPH.GetGlobalVar<string>(\"pokemonGamePath\");",
        "        if (string.IsNullOrWhiteSpace(gameRoot))",
        "        {",
        "            string baseDir = AppDomain.CurrentDomain.BaseDirectory;",
        "            string testPath1 = Path.Combine(baseDir, @\"GameEngine\\GameEngine.exe\");",
        "            string testPath2 = Path.Combine(baseDir, @\"Pokemon Chat Game\\GameEngine\\GameEngine.exe\");",
        "            string testPath3 = Path.Combine(baseDir, @\"PokemonChatGame\\GameEngine\\GameEngine.exe\");",
        "            if (File.Exists(testPath1))",
        "            {",
        "                gameRoot = baseDir;",
        "            }",
        "            else if (File.Exists(testPath2))",
        "            {",
        "                gameRoot = Path.Combine(baseDir, \"Pokemon Chat Game\");",
        "            }",
        "            else if (File.Exists(testPath3))",
        "            {",
        "                gameRoot = Path.Combine(baseDir, \"PokemonChatGame\");",
        "            }",
        "            else",
        "            {",
        "                CPH.LogWarn(\"Pokemon Chat Game: GameEngine.exe not found. Please set global variable 'pokemonGamePath' to the game folder.\");",
        "                SendMsg(\"Pokemon Chat Game: Game path not configured. Set the 'pokemonGamePath' global variable in Streamer.bot settings.\");",
        "                return true;",
        "            }",
        "        }",
        "        string exe = Path.Combine(gameRoot, @\"GameEngine\\GameEngine.exe\");",
        "        if (!File.Exists(exe))",
        "        {",
        "            CPH.LogWarn(\"Pokemon Chat Game: GameEngine.exe not found at path: \" + exe);",
        "            SendMsg(\"Pokemon Chat Game: GameEngine.exe not found at: \" + exe);",
        "            return true;",
        "        }",
        f"        string command = @\"{args}\";",
        "        command = command.Trim();",
        "        string rawMessage = GetArgValue(new[] { \"message\", \"rawInput\", \"messageStripped\" });",
        "        string cmdPrefix = \"!\" + command;",
        "        if (command == \"inventory\")",
        "        {",
        "            if (string.IsNullOrWhiteSpace(rawMessage) ||",
        "                (!rawMessage.StartsWith(\"!inventory\", StringComparison.OrdinalIgnoreCase) &&",
        "                 !rawMessage.StartsWith(\"!pokedex\", StringComparison.OrdinalIgnoreCase)))",
        "            {",
        "                return true;",
        "            }",
        "        }",
        "        else if (command == \"catch\" || command == \"battle\" || command == \"accept\" || command == \"stats\")",
        "        {",
        "            if (string.IsNullOrWhiteSpace(rawMessage) ||",
        "                !rawMessage.StartsWith(cmdPrefix, StringComparison.OrdinalIgnoreCase))",
        "            {",
        "                return true;",
        "            }",
        "        }",
        "        string userName = GetArgValue(new[] { \"userName\", \"user\", \"displayName\", \"username\" });",
        "        string userArg = GetArgValue(new[] { \"input0\", \"arg1\", \"user2\", \"target\", \"opponent\" });",
        "        string arg2 = GetArgValue(new[] { \"input1\", \"arg2\" });",
        "        string processArgs = (command == \"inventory\") ? \"pokedex\" : command;",
        "",
        "        if (command == \"catch\")",
        "        {",
        "            if (!string.IsNullOrWhiteSpace(userArg))",
        "            {",
        "                processArgs += \" \" + userArg;",
        "            }",
        "            else if (!string.IsNullOrWhiteSpace(userName))",
        "            {",
        "                processArgs += \" \" + userName;",
        "            }",
        "            else",
        "            {",
        "                return true;",
        "            }",
        "        }",
        "        else if (command == \"pokedex\" || command == \"inventory\")",
        "        {",
        "            if (!string.IsNullOrWhiteSpace(userArg))",
        "            {",
        "                processArgs += \" \" + userArg;",
        "            }",
        "            else if (!string.IsNullOrWhiteSpace(userName))",
        "            {",
        "                processArgs += \" \" + userName;",
        "            }",
        "            else",
        "            {",
        "                return true;",
        "            }",
        "        }",
        "        else if (command == \"battle\")",
        "        {",
        "            if (string.IsNullOrWhiteSpace(userName) || string.IsNullOrWhiteSpace(userArg) || string.IsNullOrWhiteSpace(arg2)) return true;",
        "            processArgs += \" \" + userName + \" \" + userArg + \" \" + arg2;",
        "        }",
        "        else if (command == \"accept\")",
        "        {",
        "            if (string.IsNullOrWhiteSpace(userName) || string.IsNullOrWhiteSpace(userArg) || string.IsNullOrWhiteSpace(arg2)) return true;",
        "            processArgs += \" \" + userName + \" \" + userArg + \" \" + arg2;",
        "        }",
        "        else if (command == \"stats\")",
        "        {",
        "            if (string.IsNullOrWhiteSpace(userName) || string.IsNullOrWhiteSpace(userArg)) return true;",
        "            processArgs += \" \" + userName + \" \" + userArg;",
        "        }",
        "",
        "        var psi = new ProcessStartInfo",
        "        {",
        "            FileName = exe,",
        "            Arguments = processArgs,",
        "            UseShellExecute = false,",
        "            RedirectStandardOutput = true,",
        "            RedirectStandardError = true,",
        "            CreateNoWindow = true,",
        "            WorkingDirectory = gameRoot,",
        "            StandardOutputEncoding = System.Text.Encoding.UTF8,",
        "            StandardErrorEncoding = System.Text.Encoding.UTF8",
        "        };",
        "        psi.EnvironmentVariables[\"PYTHONIOENCODING\"] = \"utf-8\";",
        "",
        "        var process = Process.Start(psi);",
        "        string error = string.Empty;",
        "        if (process != null)",
        "        {",
        "            var stderrTask = System.Threading.Tasks.Task.Run(() => process.StandardError.ReadToEnd());",
        "            while (!process.StandardOutput.EndOfStream)",
        "            {",
        "                string line = process.StandardOutput.ReadLine();",
        "                if (!string.IsNullOrWhiteSpace(line))",
        "                {",
        "                    string msg = line.Trim();",
        "                    if (msg.StartsWith(\"[UPDATE_NOTIFICATION]\"))",
        "                    {",
        "                        string newVer = msg.Replace(\"[UPDATE_NOTIFICATION]\", \"\").Trim();",
        "                        string broadcaster = \"streamer\";",
        "                        try {",
        "                            var tw = CPH.TwitchGetBroadcaster();",
        "                            if (tw != null) broadcaster = tw.UserName;",
        "                        } catch {}",
        "                        string updateMsg = \"⚠️ @\" + broadcaster + \" A new update for Pokemon Chat Game is available (\" + newVer + \")! Download it here: https://github.com/tazod-yt/Pokemon-ChatGame/releases\";",
        "                        CPH.SendMessage(updateMsg);",
        "                        CPH.SendYouTubeMessage(updateMsg);",
        "                    }",
        "                    else if (msg.Length > 195)",
        "                    {",
        "                        string[] words = msg.Split(' ');",
        "                        string chunk = \"\";",
        "                        foreach (var word in words)",
        "                        {",
        "                            if (chunk.Length + word.Length + 1 > 195)",
        "                            {",
        "                                SendMsg(chunk.Trim());",
        "                                System.Threading.Thread.Sleep(800);",
        "                                chunk = word;",
        "                            }",
        "                            else",
        "                            {",
        "                                chunk += \" \" + word;",
        "                            }",
        "                        }",
        "                        if (!string.IsNullOrWhiteSpace(chunk))",
        "                        {",
        "                            SendMsg(chunk.Trim());",
        "                        }",
        "                    }",
        "                    else",
        "                    {",
        "                        SendMsg(msg);",
        "                    }",
        "                }",
        "            }",
        "            process.WaitForExit();",
        "            error = stderrTask.Result;",
        "        }",
        "        else",
        "        {",
        "            return true;",
        "        }",
        "        if (!string.IsNullOrWhiteSpace(error))",
        "        {",
        "            CPH.LogWarn(\"GameEngine error: \" + error.Trim());",
        "        }",
        "        return true;",
        "    }",
        "}",
        "",
    ]
    source = "\n".join(lines)
    return base64.b64encode(source.encode("utf-8")).decode("ascii")


def make_command(name, command_text):
    return {
        "permittedUsers": [],
        "permittedGroups": ["Subscribers"],
        "id": str(uuid.uuid4()),
        "name": name,
        "enabled": True,
        "include": False,
        "mode": 0,
        "command": command_text,
        "regexExplicitCapture": False,
        "location": 0,
        "ignoreBotAccount": True,
        "ignoreInternal": True,
        "sources": 1024,
        "persistCounter": False,
        "persistUserCounter": False,
        "caseSensitive": False,
        "globalCooldown": 0,
        "userCooldown": 0,
        "group": None,
        "grantType": 0,
    }


def make_action(name, args, command_id):
    return {
        "id": str(uuid.uuid4()),
        "queue": queue,
        "enabled": True,
        "excludeFromHistory": False,
        "excludeFromPending": False,
        "name": name,
        "group": "",
        "alwaysRun": False,
        "randomAction": False,
        "concurrent": False,
        "triggers": [
            {
                "commandId": command_id,
                "id": str(uuid.uuid4()),
                "type": 401,
                "enabled": True,
                "exclusions": [],
            }
        ],
        "subActions": [
            {
                "name": None,
                "description": None,
                "references": [
                    r"C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorlib.dll"
                ],
                "byteCode": csharp_bytecode(args),
                "precompile": False,
                "delayStart": False,
                "parseVariables": True,
                "saveResultToVariable": False,
                "saveToVariable": None,
                "id": str(uuid.uuid4()),
                "weight": 0.0,
                "type": 99999,
                "parentId": None,
                "enabled": True,
                "index": 0,
            }
        ],
        "collapsedGroups": [],
    }


def make_init_action(name, args):
    return {
        "id": str(uuid.uuid4()),
        "queue": queue,
        "enabled": True,
        "excludeFromHistory": False,
        "excludeFromPending": False,
        "name": name,
        "group": "",
        "alwaysRun": False,
        "randomAction": False,
        "concurrent": False,
        "triggers": [],
        "subActions": [
            {
                "name": None,
                "description": None,
                "references": [
                    r"C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorlib.dll"
                ],
                "byteCode": csharp_bytecode(args),
                "precompile": False,
                "delayStart": False,
                "parseVariables": True,
                "saveResultToVariable": False,
                "saveToVariable": None,
                "id": str(uuid.uuid4()),
                "weight": 0.0,
                "type": 99999,
                "parentId": None,
                "enabled": True,
                "index": 0,
            }
        ],
        "collapsedGroups": [],
    }


commands = [
    make_command("spawn", "!spawn"),
    make_command("catch", "!catch"),
    make_command("inventory", "!inventory"),
    make_command("battle", "!battle"),
    make_command("accept", "!accept"),
    make_command("leaderboard", "!leaderboard"),
    make_command("stats", "!stats"),
]

actions = [
    make_action("Pokemon Chat Game Spawn", "spawn", commands[0]["id"]),
    make_action("Pokemon Chat Game Catch", "catch", commands[1]["id"]),
    make_action("Pokemon Chat Game Inventory", "inventory", commands[2]["id"]),
    make_action("Pokemon Chat Game Battle", "battle", commands[3]["id"]),
    make_action("Pokemon Chat Game Accept", "accept", commands[4]["id"]),
    make_action("Pokemon Chat Game Leaderboard", "leaderboard", commands[5]["id"]),
    make_action("Pokemon Chat Game Stats", "stats", commands[6]["id"]),
    make_init_action("Pokemon Chat Game Init", "init"),
]

export = {
    "meta": meta,
    "data": {
        "actions": actions,
        "queues": [],
        "commands": commands,
        "websocketServers": [],
        "websocketClients": [],
        "timers": [],
    },
    "version": 23,
    "exportedFrom": "1.0.4",
    "minimumVersion": "1.0.0-alpha.1",
}

out_json = os.path.join(root, "Streamerbot", "import_actions.json")
with open(out_json, "w", encoding="utf-8") as handle:
    json.dump(export, handle, indent=2)

raw = json.dumps(export, indent=2).encode("utf-8")
blob = b"SBAE" + gzip.compress(raw)
out_txt = os.path.join(root, "Streamerbot", "import_actions.txt")
with open(out_txt, "w", encoding="utf-8") as handle:
    handle.write(base64.b64encode(blob).decode("ascii"))

print("Wrote", out_json)
print("Wrote", out_txt)
